on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: 165.22.35.8
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        port: 22
        protocol: ftps
        server-dir: /var/www/flow14.com/subdomains/memex/
